apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: config-service-git-password
  namespace: config-service
spec:
  encryptedData:
    git-password: AgApj97iUFSGJnSzBFNQ+4ctpqx0z6NLmB9m3EmPItEzSB3LWQhw123L5vwdcduExG4cKHmMutiC+K16WrfmitIxzLOgAkpg9gSKXo80s/tuMW0PlCncw+loXBiSVeTTKtM5EWmDnhBEUPTk4L4aC2EnboBVyOqxthJ/0b5ZXTIlPrjsJJ26WjuByw+bT8PzYhFOvYfEiQp7icFNzi0VF7Nii+1/sxj9z1DkRxZdxB2wJUVAArGl/UN/BxtHbMLdU1u1EXxgD2pqYZI9Af3Y2E2mAftEM3q0jWtp2AJVSO3a0CdKmTCTTNqad8zPcZ/kRAFZziHTPRCBiTLBncV8c1EBB3ESAe10pwc3UMAmItWqpZY12maqbbYzMYsiSYC/BZKeRW2SwbjcNiHObfYbYcymqzVK4iqTjfhGxbax8lo0KAuqJ1GBaxdG5UhLQtel0dkxLrbXJTAAdtBy77g0VgQx9bXjbofCFobWW1QJM8A7OCALLs+BzXy/N7prZNonYJkmgoQwR3EV/Ipr0TUqOg4IvLwB3QTb+c18JN3+T7epK5jgEpMPllJJDcbsbayLJFtzZfm2KCt3EkniE47iiul0Xig1JpjiFV64IZT4mqbczRyg6TOc0TxDD74xQ67oc11qVnxzwnsPHOTlsZGmbiaIstce54w0U/lFAYkN1JxnlxTpajMBJRJOXiyWtunjJ2eSFrfyHTKS25qrxPzebg==
  template:
    metadata:
      creationTimestamp: null
      name: config-service-git-password
      namespace: config-service

