apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- ./../../../../../../apps/base-line-monitoring/1.0

namespace: base-line-monitoring

configMapGenerator:
- name: configuration-ipaddresses
  behavior: replace
  files:
  - ipaddresses.config.json

